version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - ./localstack:/var/lib/localstack
